/*
 * Disciplina: Programação Orientada Objetos 2 
 * Prof.Dr.Ivan Ricarte
 * Curso: Tec.Análise e Desenvolvimento de Sistemas
 */
package br.ftunicamp.veterinaria.view;

import br.ftunicamp.veterinaria.control.VeterinarioControle;
import br.ftunicamp.veterinaria.model.Veterinario;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiag
 */
public class TelaVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaVeterinario
     */
    VeterinarioControle veterinarioControle = new VeterinarioControle();
    Veterinario veterinario = new Veterinario();

    public TelaVeterinario() {
        initComponents();
        preencherTabelaVeterinario();
    }

    private void preencherTabelaVeterinario() {
        DefaultTableModel tabela = (DefaultTableModel) tabelaVeterinario.getModel();
        tabela.setNumRows(0);
        List<Veterinario> veterinarios = new ArrayList<Veterinario>();
        VeterinarioControle veterinarioControle = new VeterinarioControle();
        try {
            veterinarios = veterinarioControle.listar();
            for (Veterinario v : veterinarios) {
                tabela.addRow(new Object[]{
                    v.getNome(),
                    v.getNascimentoPessoa(),
                    v.getCep(),
                    v.getEstado(),
                    v.getCidade(),
                    v.getBairro(),
                    v.getRua(),
                    v.getNumCasa(),
                    v.getTelefone(),
                    v.getGenero(),
                    v.getEmail(),
                    v.getSalario()
                });
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNacimento = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblBairoo = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVeterinario = new javax.swing.JTable();
        btnInserir1 = new javax.swing.JButton();
        lblSalario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        radioone = new javax.swing.JRadioButton();
        radiotwo = new javax.swing.JRadioButton();
        nascimento = new com.toedter.calendar.JCalendar();
        lblSuccess = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtSalario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblNacimento.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNacimento.setText("Nascimento");

        lblEstado.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblEstado.setText("Estado");

        lblCep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCep.setText("CEP");

        lblCidade.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCidade.setText("Cidade");

        lblNumero.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNumero.setText("Número");

        lblBairoo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblBairoo.setText("Bairro");

        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });

        lblRua.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblRua.setText("Rua");

        lblGenero.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblGenero.setText("Gênero");

        lblTelefone.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");

        lblEmail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        tabelaVeterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nascimento", "CEP", "Estado", "Cidade", "Bairro", "Rua", "Número", "Telefone", "Gênero", "Email", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeterinarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaVeterinario);

        btnInserir1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnInserir1.setForeground(new java.awt.Color(0, 51, 204));
        btnInserir1.setText("Inserir");
        btnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir1ActionPerformed(evt);
            }
        });

        lblSalario.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblSalario.setText("Salário");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/icon/guard-icon.png"))); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 51, 255));
        btnBuscar.setText("Buscar por nome");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        btnAtualizar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 51, 204));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnRemover.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(0, 51, 204));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        radioone.setText("M");

        radiotwo.setText("F");

        lblSuccess.setForeground(new java.awt.Color(51, 51, 255));
        lblSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCep)
                        .addGap(18, 18, 18)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado)
                        .addGap(10, 10, 10)
                        .addComponent(txtEstado))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblBairoo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblNumero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNome)
                            .addGap(10, 10, 10)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNacimento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRua)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblSalario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiotwo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInserir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNacimento)
                            .addComponent(nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCep)
                            .addComponent(lblEstado)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBairoo)
                                    .addComponent(lblNumero)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRua)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblGenero)
                                    .addComponent(radioone)
                                    .addComponent(radiotwo)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSalario)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblSuccess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void btnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserir1ActionPerformed
        // TODO add your handling code here:
        Veterinario veterinario = new Veterinario();
        VeterinarioControle veterinarioControle = new VeterinarioControle();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date dateStr;
        try {
            dateStr = formatter.parse(formatter.format(nascimento.getCalendar().getTime()));
            veterinario.setCodPessoa(0);
            veterinario.setCpf(txtCpf.getText());
            veterinario.setNome(txtNome.getText());
            veterinario.setNascimentoPessoa(formatter.format(dateStr));
            veterinario.setCep(txtCep.getText());
            veterinario.setEstado(txtEstado.getText());
            veterinario.setCidade(txtCidade.getText());
            veterinario.setBairro(txtBairro.getText());
            veterinario.setRua(txtRua.getText());
            veterinario.setTelefone(txtTelefone.getText());
            veterinario.setTipo(2); //veterinario
            veterinario.setNumCasa(Integer.parseInt(txtNumero.getText()));
            veterinario.setEmail(txtEmail.getText());
            if(radioone.isSelected()){
                veterinario.setGenero(radioone.getText());
            }else{
                if(radiotwo.isSelected())
                    veterinario.setGenero(radiotwo.getText());
            }
            veterinario.setSalario(Float.parseFloat(txtSalario.getText()));
            veterinarioControle.insertPessoa(veterinario);
            preencherTabelaVeterinario();
            lblSuccess.setText("Veterinario " + veterinario.getNome() + " cadastrador com sucesso!");
            limparTela();
            TelaConsulta consulta = new TelaConsulta();
            consulta.preencherCombo();
        } catch (ParseException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Neste campo é permitido somente numeros","Erro", 0);
        }
    }//GEN-LAST:event_btnInserir1ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        TelaConsultaVeterianaio telaConsultaVeterianaio = new TelaConsultaVeterianaio();
        telaConsultaVeterianaio.setVisible(true);
        telaConsultaVeterianaio.setLocationRelativeTo(null);
        //consultas.listarConsultas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        VeterinarioControle veterinarioControle = new VeterinarioControle();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date dateStr;
        try {
            dateStr = formatter.parse(formatter.format(nascimento.getCalendar().getTime()));
            veterinario.setCodPessoa(tabelaVeterinario.getSelectedRow());
            veterinario.setCpf(txtCpf.getText());
            veterinario.setNome(txtNome.getText());
            veterinario.setNascimentoPessoa(formatter.format(dateStr));
            veterinario.setCep(txtCep.getText());
            veterinario.setEstado(txtEstado.getText());
            veterinario.setCidade(txtCidade.getText());
            veterinario.setBairro(txtBairro.getText());
            veterinario.setRua(txtRua.getText());
            veterinario.setTelefone(txtTelefone.getText());
            veterinario.setTipo(2); //veterinario
            veterinario.setNumCasa(Integer.parseInt(txtNumero.getText()));
            veterinario.setEmail(txtEmail.getText());
            if(radioone.isSelected()){
                veterinario.setGenero(radioone.getText());
            }else{
                if(radiotwo.isSelected())
                    veterinario.setGenero(radiotwo.getText());
            }
            veterinario.setSalario(Float.parseFloat(txtSalario.getText()));
            veterinarioControle.atualizarPessoa(veterinario, tabelaVeterinario.getSelectedRow());
            preencherTabelaVeterinario();
            lblSuccess.setText("Veterinario " + veterinario.getNome() + " atualizado com sucesso!");
            limparTela();
            TelaConsulta consulta = new TelaConsulta();
            consulta.preencherCombo();
        } catch (ParseException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Neste campo é permitido somente numeros","Erro", 0);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        VeterinarioControle animalControle = new VeterinarioControle();
        animalControle.remover(tabelaVeterinario.getSelectedRow());
        lblSuccess.setText("Veterinario " + veterinario.getNome() + " removido com sucesso!");
        limparTela();
        preencherTabelaVeterinario();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tabelaVeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeterinarioMouseClicked
        List<Veterinario> veterinarios = new ArrayList<Veterinario>();
        VeterinarioControle veterinarioControle = new VeterinarioControle();
        veterinarios = veterinarioControle.listar();
        veterinario = veterinarios.get(tabelaVeterinario.getSelectedRow());//pegar os valores da linha e coluna       
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date dateStr;
        try {
            dateStr = formatter.parse(formatter.format(nascimento.getCalendar().getTime()));
            txtCpf.setText(veterinario.getCpf());
            txtNome.setText(veterinario.getNome());
            //veterinario.setNascimentoPessoa(formatter.format(dateStr));
            txtCep.setText(veterinario.getCep());
            txtEstado.setText(veterinario.getEstado());
            txtCidade.setText(veterinario.getCidade());
            txtBairro.setText(veterinario.getBairro());
            txtRua.setText(veterinario.getRua());
            txtTelefone.setText(veterinario.getTelefone());
            //veterinario.setTipo(2); //veterinario
            txtNumero.setText(Integer.toString(veterinario.getNumCasa()));
            txtEmail.setText(veterinario.getEmail());
            if(radioone.isSelected()){
                radioone.setText(veterinario.getGenero());
            }else{
                if(radiotwo.isSelected())
                    radiotwo.setText(veterinario.getGenero());
            }
            txtSalario.setText(Float.toString(veterinario.getSalario()));

        } catch (ParseException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaVeterinarioMouseClicked

    private void limparTela() {
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            //varre todos os componentes
            Component c = getContentPane().getComponent(i);
            if (c instanceof JTextField) {
                //apaga os valores
                JTextField field = (JTextField) c;
                field.setText("");
                //System.out.println("apagando campo " + i);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInserir1;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBairoo;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JLabel lblTelefone;
    private com.toedter.calendar.JCalendar nascimento;
    private javax.swing.JRadioButton radioone;
    private javax.swing.JRadioButton radiotwo;
    private javax.swing.JTable tabelaVeterinario;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
